english/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "students#index"

  resources :languages
  resources :students do
    resources :proficiencies
  end
end

english/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

english/app/models/language.rb
class Language < ApplicationRecord
  has_many :proficiencies
  has_many :students, through: :proficiencies
end

english/app/models/proficiency.rb
class Proficiency < ActiveRecord::Base
  belongs_to :student


end

english/app/models/student.rb
class Student < ApplicationRecord
  has_many :proficiencies

end

english/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

english/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @langauges = Language.all
  end

  def show
    
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

end

english/app/controllers/proficiencies_controller.rb
class ProficienciesController < ApplicationController

  def index

  end

  def new
    @student = Student.find(params[:student_id])
    @proficiency = Proficiency.new
  end

  def create
    @student = Student.find(params[:student_id])


    @proficiency = @student.proficiencies.create(proficiency_params)
    @proficiency.save

    redirect_to student_path(@student)

  end

  def edit
    @student = Student.find(params[:student_id])
    @proficiency = Proficiency.find(params[:id])

  end

  def update
    @student = Student.find(params[:student_id])

    @proficiency = Proficiency.find(params[:id])
    @proficiency.update(proficiency_params)

    redirect_to student_path(@student)

  end

  def destroy
    @student = Student.find(params[:student_id])
    @proficiency = @student.proficiencies.find(params[:id])
    @proficiency.update(want_to_learn: nil)

    redirect_to student_path(@student)
  end

  private
  def proficiency_params
    params.require(:proficiency).permit(:fluent_in, :language_know, :want_to_learn, :language_learn, :reason)
  end

end

english/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
    @proficiencies = @student.proficiencies
  end

  def new
    @student = Student.new
    @languages = Language.all
  end


  def create
    @student = Student.create(student_params.merge(:fluencies => fluencies))

    @student.save

    redirect_to student_path(@student)
  end

  def edit
    @student = Student.find(params[:id])
    @languages = Language.all
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params.merge(:fluencies => fluencies))


    redirect_to student_path
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end



  private
  def student_params
    params.require(:student).permit(:name, :age, :admin)
  end

  def fluencies
    params[:student][:fluencies].reject{|e| e == "0"}.join(", ")
  end

end

english/app/helpers/application_helper.rb
module ApplicationHelper
end

english/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>English</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  </head>

  <body>

  <header>
    <nav>
      <a href="<%= students_path %>" id="logo">Company</a>
      <a href="<%= students_path %>">Students</a>
      <a href="<%= new_student_path %>">Sign Up</a>
      <a href="#">Login</a>

    </nav>
  </header>


    <%= yield %>






<!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

english/app/views/proficiencies/_prof_form.html.erb
<%= form_for [@student, @proficiency] do |f| %>

  <%= f.check_box :want_to_learn %>
  <%= f.label :want_to_learn %>

  <%= f.label :language %>
  <%= f.collection_select :language_learn, Language.all, :language, :language %>

  <%= f.label :reason %>
  <%= f.text_field :reason %>

  <%= f.submit %>

<% end %>

english/app/views/proficiencies/edit.html.erb
<h2>Edit </h2>

<%= render "prof_form" %>

english/app/views/proficiencies/new.html.erb
<h2>Add Proficiencies</h2>

<%= render "prof_form" %>

english/app/views/students/_form.html.erb
<%= form_for @student do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :age %><br>
  <%= f.text_field :age %><br>

  Fluent Languages: <br> 
  <% @languages.each do |language| %>
    <label for=""><%= language.language %>
      <%= check_box :student, :fluencies, {:multiple => true}, language.language %><br>
    </label>

  <% end %>

  <%= f.submit %>

<% end %>

english/app/views/students/edit.html.erb
<div class="container">
<h2>Edit Info</h2>
<%= render "form" %>

</div>

english/app/views/students/index.html.erb
<div class="container">
<h2>Instructors/Students</h2>

<% @students.each do |student| %>
  <% if student.admin %>
    <div>
      <p>Instructor: <%= link_to student.name, student_path(student) %></p>
    </div>
  <% else %>
    <div>
      <p>Student: <%= link_to student.name, student_path(student) %></p>
    </div>
  <% end %>

<% end %>

</div> <!--container  -->

english/app/views/students/new.html.erb
<div class="container">
<h2>Sign Up!</h2>
<%= render "form" %>
</div>

english/app/views/students/show.html.erb
<div class="container">

<div id="student">
  <p>
    <% if @student.admin %>
      <span id="student_name"><%= @student.name %>: Instructor</span>
    <% else %>
      <span id="student_name"><%= @student.name %>: Student</span>
    <% end %>
  <%= link_to "Edit", edit_student_path %>
  <%= link_to "delete", student_path(@student), method: :delete %>
  <%= link_to "What do you Want To Learn?", new_student_proficiency_path(@student) %>
  </p>
</div>

<div>
  <p id="fluency">Fluent In: <%= @student.fluencies %></p>
  <% @proficiencies.each do |proficiency| %>
    <% if proficiency.want_to_learn%>
      <p>Wants to Learn: <%= proficiency.language_learn %>
      <%= link_to "Edit", edit_student_proficiency_path(@student, proficiency) %>
      <%= link_to "Delete", student_proficiency_path(@student, proficiency), method: :delete %></p>
      <p>Why are you wanting to learn <%= proficiency.language_learn %>?</p>
        <p><%= proficiency.reason %></p>
    <% end %>
  <% end %>
</div>

<!-- container div -->
</div>